# Generated by Django 4.2 on 2024-08-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filpcardgameapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
