# Generated by Django 4.2 on 2024-09-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filpcardgameapi', '0002_card_name_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Food', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.ImageField(upload_to='apicard/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='apiimages/'),
        ),
    ]
