# Generated by Django 4.2 on 2024-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memorygame/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='value',
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='memorygame/'),
        ),
    ]
