# Generated by Django 4.2 on 2024-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0002_memorycard_remove_card_value_card_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MemoryCard',
        ),
    ]
