# Generated by Django 4.2 on 2024-08-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0003_backgroundimage_delete_memorycard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='images/')),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
    ]
